### ISSUE TITLE
can't run MHC from command line

### ISSUE THREAD

**Issue by skochinsky** [Microchip-MPLAB-Harmony/contentmanager#2]
I'd like to download Harmony for offline use (MPLAB without Internet access). I cloned this repo, installed OpenJDK and tried running it:

```
C:\Work\git\contentmanager>java -jar harmony-content-manager.jar
Error: Could not find or load main class com.microchip.contentmanager.HarmonyDownloader
```

Am I doing something wrong? The .class file seems to be present in the .jar....

**Comment by aethaniel** [comment]
@skochinsky, sorry being late on this, my apologies.
Do you still have the problem?

**Comment by skochinsky** [comment]
@aethaniel thanks for the reply. Just fetched the repo and installed fresh OpenJDK (jdk-8.0.242.08-hotspot for win x64), same error.   However, by adding `-Xdiag` I get a bit more info:

```
Error: Could not find or load main class com.microchip.contentmanager.ContentManager
java.lang.NoClassDefFoundError: javafx/application/Application
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:757)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:495)
Caused by: java.lang.ClassNotFoundException: javafx.application.Application
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
	... 13 more

```

**Comment by aethaniel** [comment]
Thanks, we will investigate on that early next week. Sorry for the inconvenience.
I don't have any issue running Content Manager by double clicking on it in my Windows 10 File Explorer but I'm not using OpenJDK

**Comment by kkathirvel** [comment]
@skochinsky Looks like your OpenJDK wasn't downloaded with Javafx support.

please choose "JRE FX" or "JDK FX" for Java package option when you download OpenJDK and try again.

**Comment by omnyacoustics** [comment]
For Ubuntu 20.04 LTS users, the openjdk-8 package from apt-get does not include the FX packages, nor could I get it to work after installing the openjfx apt package. As mentioned in the README for this repo, I ended up getting a deb package from Zulu. See [here](https://stackoverflow.com/questions/61783369/install-openjdkopenjfx-8-on-ubuntu-20) for further details.

**Comment by topherbuckley** [comment]
For Ubuntu 20.04 LTS users, the openjdk-8 package from apt-get does not include the FX packages, nor could I get it to work after installing the openjfx apt package. As mentioned in the README for this repo, I ended up getting a deb package from Zulu. See [here](https://stackoverflow.com/questions/61783369/install-openjdkopenjfx-8-on-ubuntu-20) for further details.
