### ISSUE TITLE
crash in linux x86_64

### ISSUE THREAD

**Issue by rbras** [Microchip-MPLAB-Harmony/contentmanager#4]
contentmanager uses all the memory until it is killed by the system. It is impossible to install the packages.
Tried it from mplabx and standalone.

Tried java distributed with mplabx, system java and zulu8.42.0.23, the behaviour is the same.

**Comment by kkathirvel** [comment]
Is it happening even if you download packages one by one?

Please share your **<home-folder>/.mh3/mhc.log** file

**Comment by rbras** [comment]
Yes. I just tried downloading mhc (it selected another 2 packages) and it used all my memory (32GB) and crashed. I do not have mhc.log, only content-manager-log.txt and nbm-content-manager-launcher-log.txt. I am attaching those 2 files.
[content-manager-log.txt](https://github.com/Microchip-MPLAB-Harmony/contentmanager/files/4224591/content-manager-log.txt)
[nbm-content-manager-launcher-log.txt](https://github.com/Microchip-MPLAB-Harmony/contentmanager/files/4224592/nbm-content-manager-launcher-log.txt)

**Comment by aethaniel** [comment]
@rbras, which linux distribution are you using?

**Comment by rbras** [comment]
Fedora 31

**Comment by nplevr** [comment]
Even worse here, Ubuntu 9.10 converted to Kubuntu with 32GB ram X freezes when content manager runs for a while because all free memory is utilized!!!

**Comment by nplevr** [comment]
I tried and overwritten the provided jre with the latest v8 (jdk1.8.0_241) from oracle but still doesn't work properly and I finally got some exceptions

/microchip/mplabx/v5.35/sys/java/jre1.8.0_181/bin/java -jar /Harmony3/contentmanager/harmony-content-manager.jar
Μαρ 21, 2020 11:00:51 ΜΜ javafx.fxml.FXMLLoader$ValueElement processValue
WARNING: Loading FXML document with JavaFX API of version 8.0.201 by JavaFX runtime of version 8.0.181
com.microchip.downloader.PathController.testResult()Success
Creating Intial Loading Screen..
Catalog information Success, Now switching to Downloader UI
**This was with original JRE of 181 and we get a warning concering the JavaFX API ver**

/microchip/mplabx/v5.35/sys/java/jre1.8.0_181/bin/java -jar /Harmony3/contentmanager/harmony-content-manager.jar
com.microchip.downloader.PathController.testResult()Success
Creating Intial Loading Screen..
Catalog information Success, Now switching to Downloader UI
Killed
**This was with JRE of 212**
**This is the last try with the latest 241, old folder name is used so MPLABX can start from the shortcut**
/microchip/mplabx/v5.35/sys/java/jre1.8.0_181/bin/java -jar /Harmony3/contentmanager/harmony-content-manager.jar
com.microchip.downloader.PathController.testResult()Success
Creating Intial Loading Screen..
Exception in thread "pool-2-thread-1" Catalog information Success, Now switching to Downloader UI
java.util.concurrent.RejectedExecutionException: Task com.microchip.contentmanager.logging.Logger$$Lambda$64/1392111501@1e07a8c0 rejected from java.util.concurrent.ThreadPoolExecutor@354eb28f[Shutting down, pool size = 1, active threads = 1, queued tasks = 0, completed tasks = 183]
        at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2063)
        at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:830)
        at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1379)
        at com.microchip.contentmanager.logging.Logger.log(Logger.java:56)
        at com.microchip.contentmanager.logging.Logger.error(Logger.java:72)
        at com.microchip.contentmanager.logging.Log.offer(Logger.java:158)
        at com.microchip.contentmanager.logging.Logger.lambda$log$0(Logger.java:56)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Exception in thread "readLocalRepository dev_packs" java.util.concurrent.RejectedExecutionException: Task com.microchip.contentmanager.logging.Logger$$Lambda$64/1392111501@5fd9f99c rejected from java.util.concurrent.ThreadPoolExecutor@354eb28f[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 184]
        at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2063)
        at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:830)
        at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1379)
        at com.microchip.contentmanager.logging.Logger.log(Logger.java:56)
        at com.microchip.contentmanager.logging.Logger.warn(Logger.java:68)
        at com.microchip.contentmanager.git.LocalRepo.updatePackage(LocalRepo.java:88)
        at com.microchip.contentmanager.git.GitService.readLocalRepository(GitService.java:407)
        at com.microchip.contentmanager.git.GitService.access$000(GitService.java:67)
        at com.microchip.contentmanager.git.GitService$1.run(GitService.java:261)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OSException in thread "readLocalRepository gfx" java.util.concurrent.RejectedExecutionException: Task com.microchip.contentmanager.logging.Logger$$Lambda$64/1392111501@d0b6e18 rejected from java.util.concurrent.ThreadPoolExecutor@354eb28f[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 184]
        at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2063)
        at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:830)
        at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1379)
        at com.microchip.contentmanager.logging.Logger.log(Logger.java:56)
        at com.microchip.contentmanager.logging.Logger.debug(Logger.java:60)
        at com.microchip.contentmanager.git.GitService.readLocalRepository(GitService.java:418)
        at com.microchip.contentmanager.git.GitService.access$000(GitService.java:67)
        at com.microchip.contentmanager.git.GitService$1.run(GitService.java:261)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OSException in thread "readLocalRepository usb" java.util.concurrent.RejectedExecutionException: Task com.microchip.contentmanager.logging.Logger$$Lambda$64/1392111501@462aca63 rejected from java.util.concurrent.ThreadPoolExecutor@354eb28f[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 184]
        at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2063)
        at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:830)
        at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1379)
        at com.microchip.contentmanager.logging.Logger.log(Logger.java:56)
        at com.microchip.contentmanager.logging.Logger.debug(Logger.java:60)
        at com.microchip.contentmanager.git.GitService.readLocalRepository(GitService.java:418)
        at com.microchip.contentmanager.git.GitService.access$000(GitService.java:67)
        at com.microchip.contentmanager.git.GitService$1.run(GitService.java:261)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^[OS^C:~$ 
`

**Comment by nplevr** [comment]
It looks like after updating my Kubuntu 9.10 with latest [Liquorix](https://liquorix.net/) 5.5.0 Linux Kernel (has 5.3.0+ officially) AND updating mesa [drivers] (https://launchpad.net/~oibaf/+archive/ubuntu/graphics-drivers) to version 20.1.0-devel  (git-5cc3ab0 2020-03-21 eoan-oibaf-ppa)
 for my AMD Radeon RX570 there are no more memory leaks and works
